# permissions for end users to edit aiopsanalyzers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aiopsanalyzer
    app.kubernetes.io/managed-by: kustomize
  name: aiopsanalyzer-editor-role
rules:
- apiGroups:
  - autofix.aiops.com
  resources:
  - aiopsanalyzers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autofix.aiops.com
  resources:
  - aiopsanalyzers/status
  verbs:
  - get
